// storybook-vue/shared/components/component/vue/atom/Input/variant/Input.vue
<template>
  <input
    :type="type"
    :value="value"
    :placeholder="placeholder"
    :disabled="disabled"
    :class="['input', `input--${themeColor}`, `input--${size}`]"
    @input="handleInput"
  />
</template>

<script setup>
import './Input.css';

const props = defineProps({
  value: {
    type: [String, Number],
    default: ''
  },
  placeholder: {
    type: String,
    default: ''
  },
  type: {
    type: String,
    default: 'text'
  },
  themeColor: {
    type: String,
    default: 'default',
    validator: (value) => ['default', 'transparent', 'primary', 'warning'].includes(value)
  },
  size: {
    type: String,
    default: 's',
    validator: (value) => ['s', 'm', 'l', 'xl'].includes(value)
  },
  disabled: {
    type: Boolean,
    default: false
  }
});

const emit = defineEmits(['update:value']);

const handleInput = (event) => {
  emit('update:value', event.target.value);
};
</script>

// shared/components/component/react/atom/Input/Input.tsx
import React from "react";
// Use vanilla-extract
import { InputCss } from "./Input.css";
import { theme } from "../../../../../../shared/assets/style/theme/theme.css";
 
interface InputProps {
    placeholder : string;
    value? : string;
    type : 'text'|'number'|'password';
    themeColor? : "default" | "transparent" | "primary" | "warring";
    size? : "s" | "m" | "l" | "xl"; 
    disabled? : boolean;
    onChange? : ()=> void;
}

export default function Input({type, themeColor, disabled, size, placeholder}:InputProps) {
    return (
        <input className={`${theme} ${InputCss({
            size : size,
            themeColor : themeColor,
        })}`} 
            type={type} 
            placeholder={placeholder}
            defaultValue={''} 
            disabled={disabled}
        />
    )
}
